In [1]:
import jax.numpy as jnp
from jax import random, grad, vmap, jit

key = random.PRNGKey(0)



In [2]:
ws = [random.normal(key, (3, 3)) * jnp.sqrt(2 / (3 + 3)) for _ in range(10)]
bs = [jnp.zeros(1) for _ in range(10)]

X = random.normal(key, (1000, 3))
res = X
for w, b in zip(ws, bs):
    res = res @ w + b

print(res)

[[ 6.5856543   5.6028194  -6.1329246 ]
 [ 0.83098197  0.7037289  -0.7774668 ]
 [-2.1084046  -1.7890066   1.960885  ]
 ...
 [ 0.88706774  0.75228006 -0.82447726]
 [ 2.2509716   1.9133378  -2.0966735 ]
 [ 0.1786989   0.15000126 -0.16704927]]


In [3]:
ws = [random.normal(key, (3, 3)) for _ in range(10)]

X = random.normal(key, (1000, 3))
res = X
for w, b in zip(ws, bs):
    res = res @ w + b

print(res)

[[ 1600.3146   1361.4856  -1490.3013 ]
 [  201.9287    171.00618  -188.92447]
 [ -512.3426   -434.72885   476.4953 ]
 ...
 [  215.55754   182.80411  -200.34799]
 [  546.98627   464.9412   -509.49176]
 [   43.42386    36.45033   -40.593  ]]
